### ISSUE TITLE
Création d'un nouveau point de plongé

### ISSUE THREAD

**Issue by ThomasEscorne** [Kevin-Bridonneau/AtlantiqueDive#2]
Donner la possibilité à l'utilisateur le choix de donner la position du point de plonger via la carte, ou à défaut donner une indication sur la carte de où se trouve le point que l'utilisateur place en donnant les coordonnées GPS

**Comment by Kevin-Bridonneau** [comment]
Alors le problème étant que que des plongeurs vous utilisé les coordonnée dans leurs gps de bateaux et choisir un point à la volée pour proposé un site n'est pas une bonne idée. Des gens risque de se déplacer pour rien et nous faire de très mauvais retours sur la fiabilité de nos information.

**Comment by ThomasEscorne** [comment]
J'entends bien la problématique, je pense du coup que ton système est bien mais qu'il serait mieux si quand l'utilisateur rentre les coordonnées sur ton formulaire cela lui affiche où est le point sur la carte (comme cela il peut vérifier si la position est cohérente avec les coordonnées)

**Comment by Kevin-Bridonneau** [comment]
j'ai ajouter le positionnement du marqueur comme demandé, j'ai du décaler le pop up de soumission de site pour garder la vue sur la carte en même temps. Cela impact légèrement le design , à voir si la fonctionnalité plait.
