### ISSUE TITLE
Annoncer à l'utilisateur que sa demande a été prise en compte

### ISSUE THREAD

**Issue by ThomasEscorne** [Kevin-Bridonneau/AtlantiqueDive#3]
Quand un utilisateur propose un nouveau point de plongée et valide le form, le prévenir que sa proposition sera passée en revue par un administrateur via un pop-up par exemple, puis fermer le formulaire pour éviter que l'utilisateur envoie plusieurs fois la proposition.

**Comment by Kevin-Bridonneau** [comment]
Ajout d'un pop-up après soumission d'un nouveau site de plongée avec message d'avertissement.
